# Tag 1.0.0 Files size: 1.09GB (At time of creating talk)
FROM ubuntu:latest
ARG DEBIAN_FRONTEND=noninteractive
ENV APACHE_DOCUMENT_ROOT /var/www/html/public/

RUN apt-get update -y
RUN apt-get install -y software-properties-common
RUN add-apt-repository -y ppa:ondrej/php
RUN apt install -y php7.4
RUN apt install -y php7.4-*
RUN apt-get install -y git
RUN apt-get install -y zip
RUN apt-get install -y unzip
RUN apt-get install -y curl
RUN apt-get install -y apache2
RUN apt-get install -y libapache2-mod-php
RUN apt-get install -y mysql-server
RUN apt-get install -y mysql-client
RUN apt-get install -y rabbitmq-server
RUN curl -s https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer
RUN a2enmod rewrite

ADD config/sites-available/000-default.conf \
    /etc/apache2/sites-available/000-default.conf

WORKDIR /var/www/html/
COPY site .

RUN composer install

EXPOSE 80
CMD apachectl -D FOREGROUND