# Tag 1.7.0 Files size:   444MB (At time of creating talk)
# Using docker multi stage builds

FROM composer:1.7 as dev-vendor
COPY site/composer.json composer.json
RUN composer install                    \
    --ignore-platform-reqs              \
    --no-interaction                    \
    --prefer-dist                    && \
    composer clearcache

FROM php:7.4-rc-apache as builder-base
ENV APACHE_DOCUMENT_ROOT /var/www/html/public/
ADD config/sites-available/000-default.conf \
    /etc/apache2/sites-available/000-default.conf

FROM builder-base as development
COPY --from=dev-vendor /app/ /var/www/html/
